FROM apache/airflow:2.9.1-python3.10

USER root
RUN apt-get update && apt-get install -y build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Download NLTK resources
RUN python -m nltk.downloader stopwords wordnet punkt -d /opt/airflow/nltk_data
